server:
  port: 8000
  context-path: /whxj
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/third_dog_account
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver